name: Release

on:
  push:
    tags:
      - v*
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: make test

      - name: Build
        run: make build
  bump_version:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump_version_and_push_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: clly/github-tag-action@1.17.2
        id: bump_version_and_push_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main,release.*
  build-docker-image:
    runs-on: ubuntu-latest
    needs: bump_version
    outputs:
      version: v0.1.0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Extract Tags
        id: extract-tags
        run: |
          set -x
          source .makefiles/scripts/tags.bash
          TAGS="${{github.repository}}:latest"
          if [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          fi
          if [[ -n $gitTag && $gitTag =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            VERSION=${gitTag}
            MINOR=${VERSION%.*}
            MAJOR=${MINOR%.*}
            TAGS="${TAGS},${{github.repository}}:${MAJOR},${{github.repository}}:${MINOR}"
          fi
          if [[ -n $VERSION ]]; then
            TAGS="${TAGS},${{github.repository}}:${VERSION}"
          fi
          TAGS="${TAGS},${{github.repository}}:${GITHUB_SHA::8}"
          echo ::set-output name=tags::${TAGS}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.extract-tags.outputs.tags }}

